In [1]:
import numpy as np

### Задание 1

In [2]:
at = np.array([[1, 2, 3, 3, 1],
               [6, 8, 11, 10, 7]])

In [3]:
a = at.transpose()

In [4]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [5]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

### Задание 2

In [6]:
a_centered = a - mean_a

In [7]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [9]:
a_centered_sp = np.dot(a_centered.T[0], a_centered.T[1])
a_centered_sp

8.0

In [13]:
N = 5
cov1 = a_centered_sp / (N - 1)
cov1

2.0

### Задание 4

In [14]:
b = np.cov(at)
b

array([[1. , 2. ],
       [2. , 4.3]])

In [15]:
cov2 = b[0, 1]
cov2

2.0